# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build Check

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check
        run: ./gradlew check

test:
  name: Test
  runs-on: ubuntu-latest
  permissions:
    checks: write
    contents: read
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
    - name: Run unit tests
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: test
    - name: Publish Test Report
      if: github.event.pull_request.head.repo.full_name == github.repository
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    - name: Upload JaCoCo coverage report
      if: github.event.pull_request.head.repo.full_name == github.repository
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: backend/build/jacoco-report/
